#!/usr/bin/env python3
"""fw integrate — Layer 2 serialized-integration preflight (T-2399, T-2397 slice 1).

This is the READ-ONLY half of the L2 integration queue (T-2397, G2 of the T-2394
structural-remediation inception). It answers, without mutating anything:

  "If I integrated this worktree branch onto master right now, would it FF cleanly,
   need L2 governance-file strategies, or need a human to resolve a real conflict?"

It encodes the un-partitionable-file taxonomy from T-2397 §3.2 as code (previously
tribal knowledge applied by hand during every reconciliation). The mutating verb
(`fw integrate run`, a later slice) will reuse `classify_path()` to apply the
per-class strategy at the join.

Conflict signal: a file changed on BOTH sides of the merge-base (master-side AND
branch-side). The taxonomy's whole point is that governance/generated files must
be regenerated/unioned even when they would *textually* merge — so "changed on
both sides" is the right signal, not "git reports a textual conflict".

Exit codes (check):
  0  ff-ready or clean    — master is an ancestor of HEAD (FF works), OR no
                            both-sided files (a plain merge is conflict-free)
  1  auto-resolvable      — both-sided files exist but ALL are governance/
                            generated classes L2 resolves mechanically
                            (regenerate / append-union / id-union / take-existing /
                            field-merge); no human judgment needed
  2  needs-human          — at least one both-sided file is real code/docs
                            (git-merge class) that may genuinely conflict
  3  not-on-a-branch      — invoked while HEAD is master/main (nothing to integrate)
  4  usage / git error
"""

import subprocess
import sys

# ── Un-partitionable file taxonomy (T-2397 §3.2) ────────────────────────────
# Each class maps to a join strategy that is NOT `git merge`. Order matters:
# the first matching rule wins, so put specific paths before broad ones.
#
# A rule is (predicate, class, strategy, needs_human). `needs_human` is the
# default disposition when this class appears on both sides of the merge-base.

def _is_task_md(p):
    return (p.startswith(".tasks/active/") or p.startswith(".tasks/completed/")) \
        and p.endswith(".md") and "/T-" in p

def _is_episodic(p):
    return p.startswith(".context/episodic/") and p.endswith(".yaml")

def _is_latest_audit(p):
    # .context/audits/**/LATEST*.yaml  and dated audit rollups regenerated by cron
    return p.startswith(".context/audits/") and p.endswith(".yaml")

# (predicate, class, strategy, needs_human)
_RULES = [
    (lambda p: p in (".context/working/.hook-counter",
                     ".context/working/.loop-detect.json",
                     ".context/working/.edit-counter",
                     ".context/working/.tool-counter"),
     "regenerate", "take target-side / reset; never merge", False),
    (lambda p: p == ".context/project/metrics-history.yaml",
     "append-union", "union append-only series by timestamp key, dedupe", False),
    (lambda p: p == ".context/working/feedback-stream.yaml",
     "append-union", "union append-only event log by digest key (T-1985)", False),
    (lambda p: p == ".context/working/reviewer-overrides.yaml",
     "id-union", "union list by `id` (OV-*)", False),
    (_is_latest_audit,
     "regenerate", "next audit/cron tick rewrites; take newest", False),
    (_is_episodic,
     "take-existing", "write-once; never overwrite a completed episodic", False),
    (_is_task_md,
     "field-merge", "frontmatter last-writer-wins by last_update; body=branch; "
                    "same-field two-writer → surface", False),
]

# Everything else is genuine source/docs that SHOULD git-merge (and may conflict).
_DEFAULT = ("git-merge", "standard 3-way merge (real code/docs)", True)


def classify_path(path):
    """Return (class, strategy, needs_human) for a repo-relative path."""
    for pred, cls, strat, nh in _RULES:
        if pred(path):
            return (cls, strat, nh)
    return _DEFAULT


# ── git helpers ─────────────────────────────────────────────────────────────

def _git(*args):
    """Run a git command, return (rc, stdout.strip())."""
    try:
        r = subprocess.run(["git", *args], capture_output=True, text=True)
        return (r.returncode, r.stdout.strip())
    except Exception as e:  # pragma: no cover - defensive
        return (127, str(e))


def _changed_files(rev_range):
    rc, out = _git("diff", "--name-only", rev_range)
    if rc != 0:
        return None
    return set(f for f in out.splitlines() if f)


# ── check command ───────────────────────────────────────────────────────────

def cmd_check(target="master"):
    rc, branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    if rc != 0:
        print(f"integrate: not a git repo or detached HEAD ({branch})", file=sys.stderr)
        return 4
    if branch in ("master", "main"):
        print(f"integrate: HEAD is '{branch}' — nothing to integrate.\n"
              f"  Run from a worktree feature branch; integration moves a branch ONTO {target}.",
              file=sys.stderr)
        return 3

    rc, _ = _git("rev-parse", "--verify", "--quiet", target)
    if rc != 0:
        print(f"integrate: target ref '{target}' not found.", file=sys.stderr)
        return 4

    rc, base = _git("merge-base", target, "HEAD")
    if rc != 0:
        print(f"integrate: no merge-base between {target} and {branch}.", file=sys.stderr)
        return 4

    ff_ready = _git("merge-base", "--is-ancestor", target, "HEAD")[0] == 0
    _, ahead = _git("rev-list", "--count", f"{target}..HEAD")
    _, behind = _git("rev-list", "--count", f"HEAD..{target}")

    print(f"Branch:     {branch}")
    print(f"Target:     {target}")
    print(f"Merge-base: {base[:12]}")
    print(f"Ahead/behind: branch +{ahead} / {target} +{behind}")
    print("")

    if ff_ready:
        print(f"✓ FF-READY — {target} is an ancestor of {branch}; "
              f"`git merge --ff-only {branch}` on {target} lands cleanly.")
        return 0

    # Diverged: find files changed on BOTH sides of the merge-base.
    master_side = _changed_files(f"{base}..{target}")
    branch_side = _changed_files(f"{base}..HEAD")
    if master_side is None or branch_side is None:
        print("integrate: failed to diff against merge-base.", file=sys.stderr)
        return 4
    both = sorted(master_side & branch_side)

    if not both:
        print(f"✓ CLEAN-MERGE — {target} diverged (+{behind}) but touches no files this "
              f"branch also changed; `git merge {target}` here is conflict-free, then FF.")
        return 0

    # Classify each both-sided file.
    buckets = {}
    needs_human = False
    for p in both:
        cls, strat, nh = classify_path(p)
        buckets.setdefault(cls, []).append((p, strat))
        if nh:
            needs_human = True

    print(f"⚠ DIVERGED with {len(both)} file(s) changed on both sides "
          f"({target} and {branch}). Per-file integration strategy (T-2397 §3.2):")
    print("")
    # Stable, readable ordering: human-needed class first.
    order = ["git-merge", "field-merge", "id-union", "append-union",
             "regenerate", "take-existing"]
    for cls in order:
        if cls not in buckets:
            continue
        tag = "  NEEDS HUMAN" if cls == "git-merge" else "  auto"
        print(f"[{cls}]{tag}")
        for p, strat in buckets[cls]:
            print(f"    {p}")
            print(f"        → {strat}")
    print("")

    if needs_human:
        print("Verdict: NEEDS-HUMAN — real code/docs changed on both sides; "
              "a 3-way merge here may conflict. Resolve in this worktree "
              f"(`git merge {target}`), then the operator FFs {target}.")
        return 2
    print("Verdict: AUTO-RESOLVABLE — all both-sided files are governance/generated "
          "classes L2 resolves mechanically; no human judgment needed. "
          f"`git merge {target}` here, apply per-class strategy, then FF {target}.")
    return 1


def cmd_classify(paths):
    """Classify one or more paths (debug / scripting helper)."""
    for p in paths:
        cls, strat, nh = classify_path(p)
        flag = "needs-human" if nh else "auto"
        print(f"{p}\t{cls}\t{flag}\t{strat}")
    return 0


# ── run command (mutating merge-back, T-2397 §3) ─────────────────────────────
# MVP: integrate TARGET's divergence INTO the current worktree branch, auto-
# resolving both-sided governance/generated conflicts via the taxonomy, around
# any regenerable working-tree churn. After this the worktree branch ⊇ target,
# so target FFs to it cleanly. The final FF of target (often checked out / dirty
# elsewhere) is reported, or done server-side with --push.
#
# Deferred (follow-up slice): true append/id/field UNION at both-sided conflicts.
# This MVP keeps the integrating branch's version ("ours") for the auto classes
# (body=branch is authoritative per §3.2) and only ABORTS on a real code conflict.

import os
import time

_LOCK_TTL = 900  # seconds; a lock older than this (or with a dead pid) is stale


def _git_rc(*args):
    """Run git, return rc only (stderr surfaced to caller's stderr on failure)."""
    try:
        r = subprocess.run(["git", *args], capture_output=True, text=True)
        if r.returncode != 0 and r.stderr.strip():
            print(r.stderr.strip(), file=sys.stderr)
        return r.returncode
    except Exception as e:  # pragma: no cover - defensive
        print(str(e), file=sys.stderr)
        return 127


def _pid_alive(pid):
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, ValueError):
        return False
    except PermissionError:
        return True  # exists, owned by another user


def _lock_path():
    rc, gcd = _git("rev-parse", "--git-common-dir")
    if rc != 0:
        return None
    if not os.path.isabs(gcd):
        gcd = os.path.abspath(gcd)
    return os.path.join(gcd, ".fw-integrate.lock")


def _acquire_lock():
    lp = _lock_path()
    if not lp:
        return (False, "no git-common-dir")
    if os.path.exists(lp):
        try:
            pid_s, ts_s = open(lp).read().split()[:2]
            age = int(time.time()) - int(ts_s)
            if _pid_alive(int(pid_s)) and age < _LOCK_TTL:
                return (False, f"integration lock held by pid {pid_s} (age {age}s) — {lp}")
        except Exception:
            pass  # corrupt/stale → reclaim
    with open(lp, "w") as f:
        f.write(f"{os.getpid()} {int(time.time())}\n")
    return (True, lp)


def _release_lock(lp):
    try:
        if lp and os.path.exists(lp):
            os.remove(lp)
    except OSError:
        pass


def _dirty_files():
    """Working-tree changed paths (staged + unstaged + untracked), repo-relative.

    Parses raw porcelain output directly — NOT via _git(), whose .strip() removes
    the leading space of an `XY ` status column (e.g. ` M path` → `M path`), which
    shifts the fixed `line[3:]` slice and drops the path's first character (a
    regenerable `.context/...` file then mis-classifies as real code). Each line is
    `XY PATH` with XY exactly two status chars; never lstrip the line.
    """
    try:
        r = subprocess.run(["git", "status", "--porcelain"],
                           capture_output=True, text=True)
    except Exception:  # pragma: no cover - defensive
        return []
    if r.returncode != 0:
        return []
    files = []
    for line in r.stdout.split("\n"):
        if len(line) > 3:
            path = line[3:].strip().strip('"')
            if " -> " in path:          # rename: 'R  old -> new' → take new
                path = path.split(" -> ", 1)[1]
            files.append(path)
    return files


def cmd_run(target="master", dry_run=False, push=False):
    rc, branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    if rc != 0:
        print(f"integrate run: not a git repo or detached HEAD ({branch})", file=sys.stderr)
        return 4
    if branch in ("master", "main"):
        print(f"integrate run: HEAD is '{branch}' — nothing to integrate. Run from a worktree branch.",
              file=sys.stderr)
        return 3

    # 1. Preflight — reuse the read-only verdict; never blind-merge.
    print(f"── preflight: fw integrate check {target} ──")
    verdict = cmd_check(target)
    print(f"── preflight verdict: exit {verdict} "
          f"({'ff/clean' if verdict == 0 else 'auto-resolvable' if verdict == 1 else 'needs-human' if verdict == 2 else 'error'}) ──\n")
    if verdict == 2:
        print("integrate run: REFUSED — real code/docs changed on both sides (needs-human).\n"
              f"  Resolve manually in this worktree (`git merge {target}`), then re-run.", file=sys.stderr)
        return 2
    if verdict == 3:
        return 3
    if verdict not in (0, 1):
        return 4

    # Classify current churn: regenerable (safe to stash) vs real code (refuse to touch).
    dirty = _dirty_files()
    regenerable = [f for f in dirty if not classify_path(f)[2]]   # needs_human == False
    real_dirty = [f for f in dirty if classify_path(f)[2]]
    if real_dirty:
        print("integrate run: REFUSED — uncommitted REAL code/doc changes in this worktree:",
              file=sys.stderr)
        for f in real_dirty[:10]:
            print(f"    {f}", file=sys.stderr)
        print("  Commit or stash them first; integrate run only quiesces generated/governance churn.",
              file=sys.stderr)
        return 2

    plan = [
        f"acquire single-writer lock ({_lock_path()})",
        f"quiesce {len(regenerable)} regenerable working-tree file(s) (stash)" if regenerable
        else "no regenerable churn to quiesce",
        f"git merge --no-ff {target} into {branch}; auto-resolve governance conflicts via taxonomy",
        "restore quiesced churn",
        "refresh vendored .agentic-framework/ (fw vendor self)",
        (f"push {branch}:{target} to origin (FF target)" if push
         else f"report how to FF {target} (no --push given)"),
        "release lock",
    ]
    if dry_run:
        print("DRY-RUN plan:")
        for i, step in enumerate(plan, 1):
            print(f"  {i}. {step}")
        return 0

    ok, lock = _acquire_lock()
    if not ok:
        print(f"integrate run: {lock}", file=sys.stderr)
        return 4
    try:
        stashed = False
        if regenerable:
            print(f"quiescing {len(regenerable)} regenerable file(s)…")
            if _git_rc("stash", "push", "--include-untracked", "-m",
                       f"fw-integrate-run {branch}", "--", *regenerable) == 0:
                stashed = True

        print(f"merging {target} into {branch}…")
        mrc = _git_rc("merge", "--no-ff", "--no-edit", target)
        if mrc != 0:
            # Conflicts — auto-resolve governance/generated classes, abort on real code.
            rc, out = _git("diff", "--name-only", "--diff-filter=U")
            conflicts = [f for f in out.splitlines() if f]
            unresolved = [f for f in conflicts if classify_path(f)[2]]
            if unresolved:
                print("integrate run: real code/doc conflict(s) — aborting (target untouched):",
                      file=sys.stderr)
                for f in unresolved[:10]:
                    print(f"    {f}", file=sys.stderr)
                _git_rc("merge", "--abort")
                if stashed:
                    _git_rc("stash", "pop")
                return 2
            # All conflicts are governance/generated → keep ours (branch authoritative, §3.2).
            for f in conflicts:
                _git_rc("checkout", "--ours", "--", f)
                _git_rc("add", "--", f)
                print(f"  auto-resolved [{classify_path(f)[0]}] {f}")
            if _git_rc("commit", "--no-edit") != 0:
                print("integrate run: failed to finalize merge commit", file=sys.stderr)
                _git_rc("merge", "--abort")
                if stashed:
                    _git_rc("stash", "pop")
                return 4

        if stashed:
            print("restoring quiesced churn…")
            _git_rc("stash", "pop")  # regenerated files win on conflict; harmless if it re-conflicts

        print("refreshing vendored .agentic-framework/…")
        _vendor_refresh()

        # FF target to the (now-superset) branch.
        if push:
            print(f"pushing {branch}:{target} to origin…")
            prc = _git_rc("push", "origin", f"{branch}:{target}")
            if prc != 0:
                print(f"integrate run: push to {target} failed (see above); branch is integrated locally.",
                      file=sys.stderr)
        else:
            print(f"\n✓ {branch} now contains {target}. To make {target} live, FF it:")
            print(f"    git push origin {branch}:{target}      # or re-run with --push")
            print(f"    (if {target} is checked out & clean elsewhere: git -C <wt> merge --ff-only {branch})")

        print(f"\n✓ integrate run complete — {branch} ⊇ {target}.")
        return 0
    finally:
        _release_lock(lock)


def _vendor_refresh():
    """Best-effort `fw vendor self`. Located via FW path env or git root."""
    fw = os.environ.get("FW_BIN") or os.environ.get("FRAMEWORK_ROOT", "")
    candidates = []
    if fw:
        candidates.append(os.path.join(fw, "bin", "fw") if os.path.isdir(fw) else fw)
    rc, root = _git("rev-parse", "--show-toplevel")
    if rc == 0:
        candidates.append(os.path.join(root, "bin", "fw"))
    for c in candidates:
        if c and os.path.exists(c):
            try:
                subprocess.run([c, "vendor", "self"], capture_output=True, text=True, timeout=120)
            except Exception:
                pass
            return


def main(argv):
    if not argv:
        print("usage: integrate.py {check [target] | classify <path>...}", file=sys.stderr)
        return 4
    sub, rest = argv[0], argv[1:]
    if sub == "check":
        return cmd_check(rest[0] if rest else "master")
    if sub == "classify":
        if not rest:
            print("usage: integrate.py classify <path>...", file=sys.stderr)
            return 4
        return cmd_classify(rest)
    if sub == "run":
        dry_run = "--dry-run" in rest
        push = "--push" in rest
        positional = [a for a in rest if not a.startswith("-")]
        target = positional[0] if positional else "master"
        return cmd_run(target, dry_run=dry_run, push=push)
    print(f"integrate.py: unknown subcommand: {sub}", file=sys.stderr)
    return 4


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
