#!/usr/bin/env python3
"""fw integrate — Layer 2 serialized-integration preflight (T-2399, T-2397 slice 1).

This is the READ-ONLY half of the L2 integration queue (T-2397, G2 of the T-2394
structural-remediation inception). It answers, without mutating anything:

  "If I integrated this worktree branch onto master right now, would it FF cleanly,
   need L2 governance-file strategies, or need a human to resolve a real conflict?"

It encodes the un-partitionable-file taxonomy from T-2397 §3.2 as code (previously
tribal knowledge applied by hand during every reconciliation). The mutating verb
(`fw integrate run`, a later slice) will reuse `classify_path()` to apply the
per-class strategy at the join.

Conflict signal: a file changed on BOTH sides of the merge-base (master-side AND
branch-side). The taxonomy's whole point is that governance/generated files must
be regenerated/unioned even when they would *textually* merge — so "changed on
both sides" is the right signal, not "git reports a textual conflict".

Exit codes (check):
  0  ff-ready or clean    — master is an ancestor of HEAD (FF works), OR no
                            both-sided files (a plain merge is conflict-free)
  1  auto-resolvable      — both-sided files exist but ALL are governance/
                            generated classes L2 resolves mechanically
                            (regenerate / append-union / id-union / take-existing /
                            field-merge); no human judgment needed
  2  needs-human          — at least one both-sided file is real code/docs
                            (git-merge class) that may genuinely conflict
  3  not-on-a-branch      — invoked while HEAD is master/main (nothing to integrate)
  4  usage / git error
"""

import subprocess
import sys

# ── Un-partitionable file taxonomy (T-2397 §3.2) ────────────────────────────
# Each class maps to a join strategy that is NOT `git merge`. Order matters:
# the first matching rule wins, so put specific paths before broad ones.
#
# A rule is (predicate, class, strategy, needs_human). `needs_human` is the
# default disposition when this class appears on both sides of the merge-base.

def _is_task_md(p):
    return (p.startswith(".tasks/active/") or p.startswith(".tasks/completed/")) \
        and p.endswith(".md") and "/T-" in p

def _is_episodic(p):
    return p.startswith(".context/episodic/") and p.endswith(".yaml")

def _is_latest_audit(p):
    # .context/audits/**/LATEST*.yaml  and dated audit rollups regenerated by cron
    return p.startswith(".context/audits/") and p.endswith(".yaml")

# (predicate, class, strategy, needs_human)
_RULES = [
    (lambda p: p in (".context/working/.hook-counter",
                     ".context/working/.loop-detect.json",
                     ".context/working/.edit-counter",
                     ".context/working/.tool-counter"),
     "regenerate", "take target-side / reset; never merge", False),
    (lambda p: p == ".context/project/metrics-history.yaml",
     "append-union", "union append-only series by timestamp key, dedupe", False),
    (lambda p: p == ".context/working/feedback-stream.yaml",
     "append-union", "union append-only event log by digest key (T-1985)", False),
    (lambda p: p == ".context/working/reviewer-overrides.yaml",
     "id-union", "union list by `id` (OV-*)", False),
    (_is_latest_audit,
     "regenerate", "next audit/cron tick rewrites; take newest", False),
    (_is_episodic,
     "take-existing", "write-once; never overwrite a completed episodic", False),
    (_is_task_md,
     "field-merge", "frontmatter last-writer-wins by last_update; body=branch; "
                    "same-field two-writer → surface", False),
]

# Everything else is genuine source/docs that SHOULD git-merge (and may conflict).
_DEFAULT = ("git-merge", "standard 3-way merge (real code/docs)", True)


def classify_path(path):
    """Return (class, strategy, needs_human) for a repo-relative path."""
    for pred, cls, strat, nh in _RULES:
        if pred(path):
            return (cls, strat, nh)
    return _DEFAULT


# ── git helpers ─────────────────────────────────────────────────────────────

def _git(*args):
    """Run a git command, return (rc, stdout.strip())."""
    try:
        r = subprocess.run(["git", *args], capture_output=True, text=True)
        return (r.returncode, r.stdout.strip())
    except Exception as e:  # pragma: no cover - defensive
        return (127, str(e))


def _changed_files(rev_range):
    rc, out = _git("diff", "--name-only", rev_range)
    if rc != 0:
        return None
    return set(f for f in out.splitlines() if f)


# ── check command ───────────────────────────────────────────────────────────

def cmd_check(target="master"):
    rc, branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    if rc != 0:
        print(f"integrate: not a git repo or detached HEAD ({branch})", file=sys.stderr)
        return 4
    if branch in ("master", "main"):
        print(f"integrate: HEAD is '{branch}' — nothing to integrate.\n"
              f"  Run from a worktree feature branch; integration moves a branch ONTO {target}.",
              file=sys.stderr)
        return 3

    rc, _ = _git("rev-parse", "--verify", "--quiet", target)
    if rc != 0:
        print(f"integrate: target ref '{target}' not found.", file=sys.stderr)
        return 4

    rc, base = _git("merge-base", target, "HEAD")
    if rc != 0:
        print(f"integrate: no merge-base between {target} and {branch}.", file=sys.stderr)
        return 4

    ff_ready = _git("merge-base", "--is-ancestor", target, "HEAD")[0] == 0
    _, ahead = _git("rev-list", "--count", f"{target}..HEAD")
    _, behind = _git("rev-list", "--count", f"HEAD..{target}")

    print(f"Branch:     {branch}")
    print(f"Target:     {target}")
    print(f"Merge-base: {base[:12]}")
    print(f"Ahead/behind: branch +{ahead} / {target} +{behind}")
    print("")

    if ff_ready:
        print(f"✓ FF-READY — {target} is an ancestor of {branch}; "
              f"`git merge --ff-only {branch}` on {target} lands cleanly.")
        return 0

    # Diverged: find files changed on BOTH sides of the merge-base.
    master_side = _changed_files(f"{base}..{target}")
    branch_side = _changed_files(f"{base}..HEAD")
    if master_side is None or branch_side is None:
        print("integrate: failed to diff against merge-base.", file=sys.stderr)
        return 4
    both = sorted(master_side & branch_side)

    if not both:
        print(f"✓ CLEAN-MERGE — {target} diverged (+{behind}) but touches no files this "
              f"branch also changed; `git merge {target}` here is conflict-free, then FF.")
        return 0

    # Classify each both-sided file.
    buckets = {}
    needs_human = False
    for p in both:
        cls, strat, nh = classify_path(p)
        buckets.setdefault(cls, []).append((p, strat))
        if nh:
            needs_human = True

    print(f"⚠ DIVERGED with {len(both)} file(s) changed on both sides "
          f"({target} and {branch}). Per-file integration strategy (T-2397 §3.2):")
    print("")
    # Stable, readable ordering: human-needed class first.
    order = ["git-merge", "field-merge", "id-union", "append-union",
             "regenerate", "take-existing"]
    for cls in order:
        if cls not in buckets:
            continue
        tag = "  NEEDS HUMAN" if cls == "git-merge" else "  auto"
        print(f"[{cls}]{tag}")
        for p, strat in buckets[cls]:
            print(f"    {p}")
            print(f"        → {strat}")
    print("")

    if needs_human:
        print("Verdict: NEEDS-HUMAN — real code/docs changed on both sides; "
              "a 3-way merge here may conflict. Resolve in this worktree "
              f"(`git merge {target}`), then the operator FFs {target}.")
        return 2
    print("Verdict: AUTO-RESOLVABLE — all both-sided files are governance/generated "
          "classes L2 resolves mechanically; no human judgment needed. "
          f"`git merge {target}` here, apply per-class strategy, then FF {target}.")
    return 1


def cmd_classify(paths):
    """Classify one or more paths (debug / scripting helper)."""
    for p in paths:
        cls, strat, nh = classify_path(p)
        flag = "needs-human" if nh else "auto"
        print(f"{p}\t{cls}\t{flag}\t{strat}")
    return 0


def main(argv):
    if not argv:
        print("usage: integrate.py {check [target] | classify <path>...}", file=sys.stderr)
        return 4
    sub, rest = argv[0], argv[1:]
    if sub == "check":
        return cmd_check(rest[0] if rest else "master")
    if sub == "classify":
        if not rest:
            print("usage: integrate.py classify <path>...", file=sys.stderr)
            return 4
        return cmd_classify(rest)
    print(f"integrate.py: unknown subcommand: {sub}", file=sys.stderr)
    return 4


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
