#!/usr/bin/env bash
# arc-015 (onboarding-shape-detection) — capture the headline mechanic firing.
#
# Regenerates docs/reports/arc-015-demo-evidence.md from a live run. This is a DEMO
# CAPTURE, not a test: it exists so `fw arc close --demo` has a wire-level artefact to
# point at. The guard that keeps the mechanic working is
# tests/unit/init_project_shape_detection.bats — this script reports that suite's result
# but does not replace it.
#
# Two disciplines this script must not lose, both learned the hard way:
#
#   1. FRESH DIRECTORY PER ECOSYSTEM. `fw init` skips the seeding block entirely on a
#      directory it has already initialised, so re-using one produces NO evidence line
#      and no mode line. Read carelessly that looks exactly like "the feature is not
#      implemented" — a false negative that nearly became a filed defect against working
#      code (T-2910 Method note).
#
#   2. env -i WITH A SCRUBBED HOME. An inherited PROJECT_ROOT/FRAMEWORK_ROOT makes `fw`
#      in a fresh directory silently operate on the WRONG project (L-009/L-020, T-1633).
#      The whole claim is about what a first-run user sees, so the capture must not run
#      in this session's environment. Same reason init_project_shape_detection.bats
#      scrubs.
#
# Usage: tests/demo/arc015_capture.sh [output.md]

set -uo pipefail

FRAMEWORK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${1:-$FRAMEWORK_ROOT/docs/reports/arc-015-demo-evidence.md}"
WORK="$(mktemp -d -t arc015-demo-XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/home"

COMMIT="$(git -C "$FRAMEWORK_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
CAPTURED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# The five ecosystems named in the arc's headline_mechanic, each seeded the way a real
# project of that shape looks. None of these carry a manifest from the pre-T-2722
# seven-entry allowlist — that is the point of the arc.
seed_dotnet() { mkdir -p "$1/MyApp"; printf '<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>\n</Project>\n' > "$1/MyApp/MyApp.csproj"; printf 'class Program { static void Main() {} }\n' > "$1/MyApp/Program.cs"; }
seed_ruby()   { printf "source 'https://rubygems.org'\ngem 'rails'\n" > "$1/Gemfile"; mkdir -p "$1/app"; printf 'class ApplicationController; end\n' > "$1/app/application_controller.rb"; }
seed_php()    { printf '{"require":{"laravel/framework":"^10.0"}}\n' > "$1/composer.json"; mkdir -p "$1/app"; printf '<?php class Kernel {}\n' > "$1/app/Kernel.php"; }
seed_make()   { printf 'all:\n\tgcc -o out main.c\n' > "$1/Makefile"; printf 'int main(void) { return 0; }\n' > "$1/main.c"; }
seed_gradle() { printf "plugins { id 'java' }\nrepositories { mavenCentral() }\n" > "$1/build.gradle"; mkdir -p "$1/src"; printf 'public class App {}\n' > "$1/src/App.java"; }

strip_ansi() { sed 's/\x1b\[[0-9;]*m//g'; }

fresh_init() {   # fresh_init <dir> — real fw init, scrubbed env, returns its output
    env -i PATH="/usr/local/bin:/usr/bin:/bin" HOME="$WORK/home" \
        timeout 300 "$FRAMEWORK_ROOT/bin/fw" init "$1" 2>&1 | strip_ansi
}

declare -a ROWS=()
human_owned_total=0
missing_clause=0

for eco in dotnet ruby php make gradle; do
    proj="$WORK/$eco"          # fresh, never reused — see discipline 1
    mkdir -p "$proj"
    "seed_$eco" "$proj"

    out="$(fresh_init "$proj")"
    found_line="$(printf '%s\n' "$out" | grep -F 'found ' | head -1 | sed 's/^ *//')"
    mode_line="$(printf '%s\n'  "$out" | grep -F 'onboarding tasks (' | head -1 | sed 's/^ *//')"

    [ -z "$found_line" ] && { found_line='**MISSING**'; missing_clause=1; }
    [ -z "$mode_line"  ] && { mode_line='**MISSING**';  missing_clause=1; }

    # Clause 3: the seeded set must be startable — zero owner: human.
    n_tasks=0; n_human=0
    for f in "$proj"/.tasks/active/*.md; do
        [ -f "$f" ] || continue
        n_tasks=$((n_tasks + 1))
        grep -qE '^owner: *human' "$f" && n_human=$((n_human + 1))
    done
    human_owned_total=$((human_owned_total + n_human))

    ROWS+=("$eco|$found_line|$mode_line|$n_tasks|$n_human")
done

# The guard that keeps this working, reported alongside the one-off demo.
suite="tests/unit/init_project_shape_detection.bats"
suite_legs="$(grep -c '^@test' "$FRAMEWORK_ROOT/$suite" 2>/dev/null || echo 0)"
suite_out="$(cd "$FRAMEWORK_ROOT" && timeout 1800 bats "$suite" 2>&1 | tail -3)"
suite_rc=$?

{
    echo "# arc-015 — demo evidence: \`fw init\` reports what it found, on five real ecosystems"
    echo
    echo "> Generated by \`tests/demo/arc015_capture.sh\`. Do not hand-edit — re-run the script."
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| Captured at | \`$CAPTURED_AT\` |"
    echo "| Framework commit | \`$COMMIT\` |"
    echo "| Arc | arc-015 \`onboarding-shape-detection\` |"
    echo
    echo "## The claim under demonstration"
    echo
    echo "arc-015's \`headline_mechanic\`, split into its three verifiable clauses:"
    echo
    echo "1. the developer **watches it report what it actually found** in the directory"
    echo "2. it **states the project shape it inferred** from that"
    echo "3. it **seeds a task set they can start working immediately** — not an"
    echo "   \`owner: human\` inception the agent is structurally forbidden to clear (F-10)"
    echo
    echo "Each row below is a **fresh** directory containing real code of that ecosystem and"
    echo "**no** manifest from the pre-T-2722 seven-entry allowlist, initialised by the real"
    echo "\`fw init\` under \`env -i\`."
    echo
    echo "## Clause 1 and 2 — what the user sees"
    echo
    echo "| ecosystem | clause 1: evidence line | clause 2: shape verdict |"
    echo "|---|---|---|"
    for r in "${ROWS[@]}"; do
        IFS='|' read -r eco fl ml _ _ <<< "$r"
        echo "| \`$eco\` | \`$fl\` | \`$ml\` |"
    done
    echo
    echo "## Clause 3 — is the seeded set actually startable?"
    echo
    echo "| ecosystem | tasks seeded | \`owner: human\` |"
    echo "|---|---|---|"
    for r in "${ROWS[@]}"; do
        IFS='|' read -r eco _ _ nt nh <<< "$r"
        echo "| \`$eco\` | $nt | $nh |"
    done
    echo
    if [ "$human_owned_total" -eq 0 ]; then
        echo "**Assertion: zero \`owner: human\` tasks across all five seeded sets.**"
        echo
        echo "Stated explicitly rather than left to be inferred from a column of zeros, because"
        echo "this is the entire F-10 failure: a greenfield-misclassified project was handed an"
        echo "\`owner: human\` inception task, which the T-532 gate then used to block every other"
        echo "edit — a first-run deadlock the agent cannot clear and the new user has no path to"
        echo "diagnose."
    else
        echo "**FAILED: $human_owned_total \`owner: human\` task(s) seeded — F-10 deadlock is back.**"
    fi
    echo
    if [ "$missing_clause" -ne 0 ]; then
        echo "**WARNING: at least one clause printed no line at all.** Before reading that as"
        echo "\"not implemented\", check the directory was fresh — \`fw init\` skips seeding"
        echo "entirely on an already-initialised directory and emits neither line."
        echo
    fi
    echo "## The guard"
    echo
    echo "A demo shows the mechanic firing once. \`$suite\` is what keeps it firing —"
    echo "$suite_legs legs, covering the four F-10 misclassifiers plus the right-reason cases."
    echo
    echo '```'
    echo "$suite_out"
    echo "exit: $suite_rc"
    echo '```'
    echo
    echo "## What this artefact does NOT establish"
    echo
    echo "- It does not show a **human** completing the onboarding set. That is arc-016's"
    echo "  persona run and arc-017's gate; this is \`fw init\`'s output only."
    echo "- It does not cover ecosystems outside the five the headline mechanic names. The"
    echo "  fix is enumeration-based, so others should follow — but \"should\" is not"
    echo "  evidence, and this artefact contains none for them."
    echo "- It is a capture at one commit (\`$COMMIT\`). It says nothing about any later one."
    echo "- **The consumers captured here are missing 7 enforcement hooks**, including"
    echo "  \`check-onboarding-gate\` — see T-2911. That is not a defect in what this"
    echo "  artefact demonstrates (\`fw init\`'s shape inference and seeding are unaffected),"
    echo "  but it means these seeded projects are NOT running the gate that keeps the"
    echo "  onboarding set clearable over time. arc-015's mechanic fires; arc-017's guard"
    echo "  on it does not, in exactly the projects shown above."
} > "$OUT"

echo "wrote $OUT"
[ "$human_owned_total" -eq 0 ] && [ "$missing_clause" -eq 0 ]
