#!/usr/bin/env bats
# T-1558 — Regression: fw doctor must warn when the cron registry declares
# more flock-wrapped jobs than the deployed crontab carries (T-1556 prevention
# #5). Origin: T-1556 destroyed all 9 orphan-prevention wrappers in production
# while the existing file-diff check stayed green — flock parity was never
# verified structurally.

load ../test_helper

setup() {
    TEST_TEMP_DIR="$(mktemp -d)"
    TEST_PROJECT="$TEST_TEMP_DIR/proj-flock-parity"
    TEST_CRON_DIR="$TEST_TEMP_DIR/etc-cron-d"
    mkdir -p "$TEST_PROJECT/.context/cron" \
             "$TEST_PROJECT/.context/working" \
             "$TEST_PROJECT/.tasks/active" \
             "$TEST_PROJECT/.tasks/completed" \
             "$TEST_PROJECT/.tasks/templates" \
             "$TEST_CRON_DIR"
    # Minimal task template so fw doctor's task scaffolding doesn't fail
    echo "# template" > "$TEST_PROJECT/.tasks/templates/default.md"
    echo "framework_root: $FRAMEWORK_ROOT" > "$TEST_PROJECT/.framework.yaml"
    export PROJECT_ROOT="$TEST_PROJECT"
    export FW_CRON_INSTALL_DIR="$TEST_CRON_DIR"
}

teardown() {
    [ -d "${TEST_TEMP_DIR:-}" ] && rm -rf "$TEST_TEMP_DIR"
}

# Slug derivation must match bin/fw's: basename | lower | non-alnum→dash
_slug() {
    basename "$TEST_PROJECT" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g'
}

# Build a minimal cron-registry.yaml with N flock-wrapped entries.
_make_registry() {
    local n="$1"
    local file="$TEST_PROJECT/.context/cron-registry.yaml"
    {
        echo "jobs:"
        for i in $(seq 1 "$n"); do
            cat <<EOF
  - id: job-$i
    name: "Job $i"
    schedule: "*/30 * * * *"
    command: "flock -n /var/lock/agentic-cron-job-$i.lock -c 'fw audit --section quality --cron'"
    source_file: agentic-audit.crontab
    origin_task: T-test
    status: active
    description: "test job $i"
EOF
        done
    } > "$file"
}

# Build a generated crontab + matching deployed crontab with M flock entries.
_make_cron_files() {
    local n="$1"  # source crontab entries
    local m="$2"  # deployed crontab flock count (m <= n simulates regression)
    local source="$TEST_PROJECT/.context/cron/agentic-audit.crontab"
    local slug; slug=$(_slug)
    local target="$TEST_CRON_DIR/agentic-audit-${slug}"
    {
        echo "# Generated by fw cron generate"
        for i in $(seq 1 "$n"); do
            echo "*/30 * * * * root flock -n /var/lock/agentic-cron-job-$i.lock -c 'fw audit --section quality --cron'"
        done
    } > "$source"
    {
        echo "# Deployed crontab"
        for i in $(seq 1 "$m"); do
            echo "*/30 * * * * root flock -n /var/lock/agentic-cron-job-$i.lock -c 'fw audit --section quality --cron'"
        done
        # Add (n - m) entries WITHOUT flock — simulates the T-1556 regression
        for i in $(seq $((m + 1)) "$n"); do
            echo "*/30 * * * * root fw audit --section quality --cron"
        done
    } > "$target"
}

@test "registry has 9 flocks, deployed has 0 — parity warning fires" {
    _make_registry 9
    _make_cron_files 9 0

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    [[ "$output" == *"Cron flock parity"* ]]
    [[ "$output" == *"registry declares 9 wrapped jobs, deployed crontab has 0"* ]]
}

@test "registry has 9 flocks, deployed has 9 — no parity warning" {
    _make_registry 9
    _make_cron_files 9 9

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    [[ "$output" != *"Cron flock parity"* ]]
}

@test "registry has 9 flocks, deployed has 5 — parity warning fires" {
    _make_registry 9
    _make_cron_files 9 5

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    [[ "$output" == *"Cron flock parity"* ]]
    [[ "$output" == *"registry declares 9 wrapped jobs, deployed crontab has 5"* ]]
}

@test "registry has 0 flocks, deployed has 0 — no parity warning (no protection to lose)" {
    # Build a registry with one job but no flock wrapper
    cat > "$TEST_PROJECT/.context/cron-registry.yaml" <<'EOF'
jobs:
  - id: bare-job
    name: "Bare"
    schedule: "* * * * *"
    command: "fw audit --section quality --cron"
    source_file: agentic-audit.crontab
    origin_task: T-test
    status: active
    description: "bare"
EOF
    local slug; slug=$(_slug)
    echo "* * * * * root fw audit --section quality --cron" > "$TEST_PROJECT/.context/cron/agentic-audit.crontab"
    cp "$TEST_PROJECT/.context/cron/agentic-audit.crontab" "$TEST_CRON_DIR/agentic-audit-${slug}"

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    [[ "$output" != *"Cron flock parity"* ]]
}

@test "missing deployed crontab — parity check is silent (existing 'not installed' warning still fires)" {
    _make_registry 9
    # Generate the source but DO NOT create the target deployed file
    {
        echo "# Generated"
        for i in $(seq 1 9); do
            echo "*/30 * * * * root flock -n /var/lock/agentic-cron-job-$i.lock -c 'fw audit'"
        done
    } > "$TEST_PROJECT/.context/cron/agentic-audit.crontab"

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    # Existing T-1112 warning still fires
    [[ "$output" == *"Cron generated but not installed"* ]]
    # New parity check is silent (no deployed file to compare against)
    [[ "$output" != *"Cron flock parity"* ]]
}
