#!/usr/bin/env bats
# T-2994: .gitignore rules that defer without naming a register entry.
#
# The load-bearing test is `the historical T-2990 block is flagged`. It replays
# the exact comment that sat in this repo's .gitignore for three months while
# 56MB of junk accumulated behind the rules it annotated. If that test passes
# and the negative control below also passes, the rail discriminates. If only
# the negative control passes, the rail is inert and looks identical to working
# — which is precisely how T-2990's first detector shipped green and useless.

setup() {
    FRAMEWORK_ROOT="${FRAMEWORK_ROOT:-/opt/999-Agentic-Engineering-Framework}"
    LIB="$FRAMEWORK_ROOT/lib/gitignore-register.sh"
    [ -f "$LIB" ] || skip "lib/gitignore-register.sh not found"
    source "$LIB"
    SB="$(mktemp -d)"
}

teardown() { rm -rf "$SB" 2>/dev/null; }

# --- positive control: the incident that caused this rail ---

@test "T-2994: the historical T-2990 block is flagged" {
    cat > "$SB/.gitignore" <<'EOF'
# Build artifacts
node_modules/

# 2nd instance (2026-05-23 session): `sys` = 14MB ImageMagick PostScript export
# with literal filename "sys", created 2026-05-16. Same class as `/os` — some
# `convert/magick` call writes a bare extensionless output name into repo root.
# Gate blocks the COMMIT; CREATION is still un-prevented (root-cause task pending).
/os
/sys
EOF
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 1 ]
    echo "$output" | grep -q 'root-cause task pending\|2nd instance'
}

@test "T-2994: naming a task in the same block clears it" {
    # Byte-identical to the block above except for the id. If this fails, the
    # rail is matching on something other than the missing reference.
    cat > "$SB/.gitignore" <<'EOF'
# T-2990: `sys` = 14MB ImageMagick PostScript export with literal filename
# "sys". Gate blocks the COMMIT; CREATION is still un-prevented (root-cause
# task pending) — tracked in T-2991.
/sys
EOF
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 0 ]
    [ -z "$output" ]
}

# --- the block, not the line, is the unit ---

@test "T-2994: a continuation line is covered by its block's id" {
    cat > "$SB/.gitignore" <<'EOF'
# T-2866: both revisit signals are generated by revisit-due-scan.sh and rely
# on an untracked marker. Do not commit it — the scan rewrites it and the
# churn is not yet worth tracking.
.revisit-due
EOF
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 0 ]
}

@test "T-2994: a blank line ends a block — the next one does not inherit its id" {
    cat > "$SB/.gitignore" <<'EOF'
# T-2866: this block names a task.
.revisit-due

# This one defers and names nothing at all, for now.
/mystery
EOF
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 1 ]
    echo "$output" | grep -q 'names nothing at all'
    # Exactly one finding — the T-2866 block must not be swept in.
    [ "$(echo "$output" | grep -c .)" -eq 1 ]
}

@test "T-2994: a pattern line ends a block too" {
    cat > "$SB/.gitignore" <<'EOF'
# T-2866: named.
.revisit-due
# unnamed, pending investigation
/mystery
EOF
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 1 ]
    [ "$(echo "$output" | grep -c .)" -eq 1 ]
}

# --- it must not fire on ordinary comments ---

@test "T-2994: ordinary descriptive comments are not findings" {
    cat > "$SB/.gitignore" <<'EOF'
# Build artifacts
node_modules/
dist/

# Editor scratch files
*.swp

# Runtime sqlite indexes
*.db
EOF
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 0 ]
    [ -z "$output" ]
}

@test "T-2994: case does not matter for the vocabulary" {
    printf '# Pending investigation, no id here\n/x\n' > "$SB/.gitignore"
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 1 ]
}

@test "T-2994: lowercase t-123 does not count as a register reference" {
    # Ids are uppercase by convention everywhere else; accepting the lowercase
    # form would let a typo silence the rail.
    printf '# pending, see t-123\n/x\n' > "$SB/.gitignore"
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 1 ]
}

# --- degenerate inputs ---

@test "T-2994: a missing .gitignore is clean, not an error" {
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 0 ]
}

@test "T-2994: an empty .gitignore is clean" {
    : > "$SB/.gitignore"
    run fw_gitignore_unregistered_defers "$SB"
    [ "$status" -eq 0 ]
}

# --- negative control: this repo, today ---

@test "T-2994: this repo's own .gitignore is clean" {
    # If this ever goes red, either someone added an unregistered deferral (fix
    # it — that is the rail working) or the vocabulary is too broad (fix that).
    run fw_gitignore_unregistered_defers "$FRAMEWORK_ROOT"
    [ "$status" -eq 0 ] || {
        echo "unregistered deferrals in .gitignore:" >&2
        echo "$output" >&2
        return 1
    }
}
