#!/usr/bin/env bats
# T-3161 — Regression: 'fw cron install' silently wiped a live deployed
# crontab when the registry declared 'jobs: []' and the deployed target
# carried jobs from the legacy heredoc lane (G-088 / 001-CashWeb field
# report). Compounding: the T-2844 empty-registry guard in `fw doctor` and
# `agents/audit/audit.sh` SKIPped the drift checks unconditionally on job
# count 0, so a project with ten live jobs read as "0 jobs — nothing to
# generate" right up until the suggested remedy (`fw cron install`) erased
# them.
#
# Pins:
#   1. install refuses when the deployed target exists and lacks the
#      registry-generated header marker (unmigrated legacy install)
#   2. install still proceeds normally when the target carries the marker
#      (registry-driven target — the normal upgrade/in-sync path)
#   3. `fw doctor` WARNs (not SKIPs) when jobs: [] AND a deployed target exists
#   4. `fw doctor` still SKIPs silently on true fresh init (jobs: [], no target)

load ../test_helper

setup() {
    TEST_TEMP_DIR="$(mktemp -d)"
    TEST_PROJECT="$TEST_TEMP_DIR/proj-t3161"
    TEST_CRON_DIR="$TEST_TEMP_DIR/etc-cron-d"
    mkdir -p "$TEST_PROJECT/.context/cron" \
             "$TEST_PROJECT/.context/working" \
             "$TEST_PROJECT/.tasks/active" \
             "$TEST_PROJECT/.tasks/completed" \
             "$TEST_PROJECT/.tasks/templates" \
             "$TEST_CRON_DIR"
    echo "# template" > "$TEST_PROJECT/.tasks/templates/default.md"
    echo "framework_root: $FRAMEWORK_ROOT" > "$TEST_PROJECT/.framework.yaml"
    export PROJECT_ROOT="$TEST_PROJECT"
    export FW_CRON_INSTALL_DIR="$TEST_CRON_DIR"
    unset FW_CRON_ALLOW_UNMIGRATED_OVERWRITE
}

teardown() {
    [ -d "${TEST_TEMP_DIR:-}" ] && rm -rf "$TEST_TEMP_DIR"
}

# Slug derivation must match bin/fw's: basename | lower | non-alnum→dash
_slug() {
    basename "$TEST_PROJECT" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g'
}

_empty_registry() {
    printf 'jobs: []\n' > "$TEST_PROJECT/.context/cron-registry.yaml"
}

# A deployed target with two live job lines, NOT carrying the registry
# generator's header marker — simulates the legacy heredoc lane's output.
_legacy_deployed_target() {
    local slug; slug=$(_slug)
    cat > "$TEST_CRON_DIR/agentic-audit-${slug}" << 'EOF'
# Legacy heredoc-installed crontab — not registry-managed
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
*/30 * * * * root echo legacy-audit-structural
0 * * * * root echo legacy-audit-traceability
EOF
}

@test "install refuses on unmigrated target: source and target both untouched, exit non-zero" {
    _empty_registry
    _legacy_deployed_target
    local slug; slug=$(_slug)
    local target="$TEST_CRON_DIR/agentic-audit-${slug}"
    local target_before; target_before=$(cat "$target")
    local source="$TEST_PROJECT/.context/cron/agentic-audit.crontab"

    run "$FRAMEWORK_ROOT/bin/fw" cron install
    [ "$status" -ne 0 ]
    [[ "$output" == *"not generated by this registry"* ]]
    [[ "$output" == *"migrate"* || "$output" == *"Migrate"* ]]

    # Target must be byte-identical to before — no write happened.
    [ "$(cat "$target")" = "$target_before" ]
    # Source must not have been (re)generated either.
    [ ! -f "$source" ]
}

@test "install with bypass env var overwrites the unmigrated target and logs Tier-2" {
    _empty_registry
    _legacy_deployed_target
    local slug; slug=$(_slug)
    local target="$TEST_CRON_DIR/agentic-audit-${slug}"

    FW_CRON_ALLOW_UNMIGRATED_OVERWRITE=1 run "$FRAMEWORK_ROOT/bin/fw" cron install
    [ "$status" -eq 0 ]
    grep -q "managed by cron-registry.yaml" "$target"
    grep -q "FW_CRON_ALLOW_UNMIGRATED_OVERWRITE" "$TEST_PROJECT/.context/working/.gate-bypass-log.yaml"
}

@test "install still works normally when the deployed target already carries the registry marker" {
    cat > "$TEST_PROJECT/.context/cron-registry.yaml" << 'EOF'
jobs:
  - id: nightly-audit
    name: "Nightly audit"
    schedule: "0 3 * * *"
    command: "fw audit --cron"
    source_file: agentic-audit.crontab
    origin_task: T-test
    status: active
    description: "test"
EOF
    local slug; slug=$(_slug)
    local target="$TEST_CRON_DIR/agentic-audit-${slug}"
    # A prior registry-driven install: carries the marker, but content differs
    # from what the current registry would generate (so install has work to do).
    cat > "$target" << 'EOF'
# Agentic Engineering Framework — Scheduled Jobs (managed by cron-registry.yaml)
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin

# stale entry
* * * * * root echo stale
EOF

    run "$FRAMEWORK_ROOT/bin/fw" cron install
    [ "$status" -eq 0 ]
    [[ "$output" != *"not generated by this registry"* ]]
    grep -q "Nightly audit" "$target"
    ! grep -q "stale entry" "$target"
}

@test "doctor WARNs when registry declares no jobs but a deployed target exists" {
    _empty_registry
    _legacy_deployed_target

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    [[ "$output" == *"Cron registry declares no jobs but a deployed crontab exists"* ]]
    [[ "$output" != *"Cron drift checks skipped — registry declares no jobs"* ]]
}

@test "doctor SKIPs silently on true fresh init: jobs: [] and no deployed target" {
    _empty_registry
    # No deployed target created.

    run "$FRAMEWORK_ROOT/bin/fw" doctor
    [[ "$output" == *"Cron drift checks skipped — registry declares no jobs (nothing to generate)"* ]]
    [[ "$output" != *"Cron registry declares no jobs but a deployed crontab exists"* ]]
}

@test "audit.sh mirrors the same WARN-vs-SKIP split as doctor" {
    _empty_registry
    _legacy_deployed_target

    run "$FRAMEWORK_ROOT/bin/fw" audit --section structure
    [[ "$output" == *"Cron registry declares no jobs but a deployed crontab exists"* ]]
}
